export enum ENUM_SEND_EMAIL_PROCESS {
    CHANGE_PASSWORD = 'CHANGE_PASSWORD',
    TEMPORARY_PASSWORD = 'TEMPORARY_PASSWORD',
    WELCOME = 'WELCOME',
    CREATE = 'CREATE',
    RESET_PASSWORD = 'RESET_PASSWORD',
    VERIFICATION = 'VERIFICATION',
    EMAIL_VERIFIED = 'EMAIL_VERIFIED',
    MOBILE_NUMBER_VERIFIED = 'MOBILE_NUMBER_VERIFIED',
}
