#!/usr/bin/env bash
# PreToolUse Write|Edit: deny secrets, generated trees, and skill output under docs/.
set -euo pipefail

path=$(jq -r '.tool_input.file_path // empty')
[ -n "$path" ] || exit 0

root="${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
rel="${path#"$root"/}"

deny() {
    jq -cn --arg reason "$1" \
        '{hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:"deny",permissionDecisionReason:$reason}}'
    exit 0
}

case "$rel" in
    .env.example|*/.env.example) ;;
    .env|.env.*|*/.env|*/.env.*)
        deny "$rel is the owner's environment file. Change .env.example and hand the variable back."
        ;;
esac

case "$rel" in
    keys/*|*/keys/*)
        deny "keys/ is generated by pnpm generate:secret and gitignored. Do not write it."
        ;;
    generated/docs/*) ;;
    generated/*|*/generated/*)
        deny "generated/ and src/generated/ are produced by pnpm generate. Reports go to generated/docs/."
        ;;
    docs/superpowers/*|*/docs/superpowers/*)
        deny "Skill output goes to .superpowers/ (gitignored). docs/ is tracked project documentation."
        ;;
esac

exit 0
