export enum EnumNotificationProcess {
    welcomeByAdmin = 'welcomeByAdmin',
    welcome = 'welcome',
    welcomeSocial = 'welcomeSocial',
    temporaryPasswordByAdmin = 'temporaryPasswordByAdmin',
    changePassword = 'changePassword',
    verifiedEmail = 'verifiedEmail',
    verifiedMobileNumber = 'verifiedMobileNumber',
    verificationEmail = 'verificationEmail',
    forgotPassword = 'forgotPassword',
    resetPassword = 'resetPassword',
    newDeviceLogin = 'newDeviceLogin',
    resetTwoFactorByAdmin = 'resetTwoFactorByAdmin',
    publishTermPolicy = 'publishTermPolicy',
    userAcceptTermPolicy = 'userAcceptTermPolicy',
    workspaceInvite = 'workspaceInvite',
    workspaceInviteUnregistered = 'workspaceInviteUnregistered',
    workspaceJoinRequest = 'workspaceJoinRequest',
    workspaceJoinAccepted = 'workspaceJoinAccepted',
    workspaceJoinRejected = 'workspaceJoinRejected',
}

export enum EnumNotificationPushProcess {
    cleanupTokens = 'cleanupTokens',
    cleanupStaleTokens = 'cleanupStaleTokens',
    resetTwoFactorByAdmin = 'resetTwoFactorByAdmin',
    temporaryPasswordByAdmin = 'temporaryPasswordByAdmin',
    resetPassword = 'resetPassword',
    newDeviceLogin = 'newDeviceLogin',
    workspaceInvite = 'workspaceInvite',
    workspaceJoinRequest = 'workspaceJoinRequest',
    workspaceJoinAccepted = 'workspaceJoinAccepted',
    workspaceJoinRejected = 'workspaceJoinRejected',
}
