export enum EnumNotificationProcess {
    welcomeByAdmin = 'welcomeByAdmin',
    welcome = 'welcome',
    welcomeSocial = 'welcomeSocial',
    temporaryPasswordByAdmin = 'temporaryPasswordByAdmin',
    changePassword = 'changePassword',
    verifiedEmail = 'verifiedEmail',
    verifiedMobileNumber = 'verifiedMobileNumber',
    verificationEmail = 'verificationEmail',
    forgotPassword = 'forgotPassword',
    resetPassword = 'resetPassword',
    newDeviceLogin = 'newDeviceLogin',
    resetTwoFactorByAdmin = 'resetTwoFactorByAdmin',
    publishTermPolicy = 'publishTermPolicy',
}
