version: 2
updates:
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'monthly'
          day: tuesday
          time: '00:00'
      open-pull-requests-limit: 3
      target-branch: 'development'
      commit-message:
          prefix: 'ci'
          include: 'scope'
      labels:
          - dependabot
      groups:
          github-actions:
              patterns:
                  - '*'

    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'monthly'
          day: monday
          time: '00:00'
      open-pull-requests-limit: 3
      target-branch: 'development'
      versioning-strategy: increase
      commit-message:
          prefix: 'chore'
          include: 'scope'
      labels:
          - dependabot
          - dependencies
      groups:
          production-dependencies:
              dependency-type: 'production'
              update-types:
                  - 'minor'
                  - 'patch'
          development-dependencies:
              dependency-type: 'development'
              update-types:
                  - 'minor'
                  - 'patch'
