allowBuilds:
    '@firebase/util': true
    '@nestjs/core': true
    '@prisma/client': true
    '@prisma/engines': true
    '@scarf/scarf': true
    '@sentry/node-cpu-profiler': true
    '@swc/core': true
    msgpackr-extract: true
    prisma: true
    protobufjs: true
    unrs-resolver: true

minimumReleaseAgeExclude:
    - yargs@18.1.0
    - '@typescript-eslint/eslint-plugin@8.66.0'
    - '@typescript-eslint/parser@8.66.0'
    - '@typescript-eslint/project-service@8.66.0'
    - '@typescript-eslint/scope-manager@8.66.0'
    - '@typescript-eslint/tsconfig-utils@8.66.0'
    - '@typescript-eslint/type-utils@8.66.0'
    - '@typescript-eslint/types@8.66.0'
    - '@typescript-eslint/typescript-estree@8.66.0'
    - '@typescript-eslint/utils@8.66.0'
    - '@typescript-eslint/visitor-keys@8.66.0'
    - bullmq@6.0.6
    - typescript-eslint@8.66.0
