allowBuilds:
    '@firebase/util': true
    '@nestjs/core': true
    '@parcel/watcher': true
    '@prisma/client': true
    '@prisma/engines': true
    '@scarf/scarf': true
    '@sentry/node-cpu-profiler': true
    '@swc/core': true
    msgpackr-extract: true
    prisma: true
    protobufjs: true
    unrs-resolver: true
