export enum ENUM_WORKER_QUEUES {
    EMAIL_QUEUE = 'EMAIL_QUEUE',
    SMS_QUEUE = 'SMS_QUEUE',
    SESSION_QUEUE = 'SESSION_QUEUE',
}

export enum ENUM_WORKER_PRIORITY {
    HIGH = 1,
    MEDIUM = 5,
    LOW = 10,
}
