export enum ENUM_AUTH_STATUS_CODE_ERROR {
    AUTH_JWT_ACCESS_TOKEN_ERROR = 5100,
    AUTH_JWT_REFRESH_TOKEN_ERROR = 5101,
    AUTH_ROLE_ACCESS_FOR_INVALID_ERROR = 5102,
    AUTH_PERMISSION_INVALID_ERROR = 5103,
    AUTH_ACCESS_FOR_INVALID_ERROR = 5104,
}
