export enum ENUM_AUTH_STATUS_CODE_ERROR {
    AUTH_JWT_ACCESS_TOKEN_ERROR = 5100,
    AUTH_JWT_REFRESH_TOKEN_ERROR = 5101,
    AUTH_PERMISSION_TOKEN_ERROR = 5102,
    AUTH_PERMISSION_TOKEN_INVALID_ERROR = 5103,
    AUTH_PERMISSION_TOKEN_NOT_YOUR_ERROR = 5104,
    AUTH_ROLE_ACCESS_FOR_INVALID_ERROR = 5105,
    AUTH_PERMISSION_INVALID_ERROR = 5106,
    AUTH_ACCESS_FOR_INVALID_ERROR = 5107,
}
