export enum ENUM_AUTH_PERMISSIONS {
    API_KEY_READ = 'API_KEY_READ',
    API_KEY_CREATE = 'API_KEY_CREATE',
    API_KEY_UPDATE = 'API_KEY_UPDATE',
    API_KEY_ACTIVE = 'API_KEY_ACTIVE',
    API_KEY_INACTIVE = 'API_KEY_INACTIVE',
    API_KEY_RESET = 'API_KEY_RESET',
    API_KEY_UPDATE_DATE = 'API_KEY_UPDATE_DATE',

    USER_READ = 'USER_READ',
    USER_CREATE = 'USER_CREATE',
    USER_UPDATE = 'USER_UPDATE',
    USER_ACTIVE = 'USER_ACTIVE',
    USER_INACTIVE = 'USER_INACTIVE',
    USER_DELETE = 'USER_DELETE',
    USER_IMPORT = 'USER_IMPORT',
    USER_EXPORT = 'USER_EXPORT',

    ROLE_CREATE = 'ROLE_CREATE',
    ROLE_UPDATE = 'ROLE_UPDATE',
    ROLE_ACTIVE = 'ROLE_ACTIVE',
    ROLE_INACTIVE = 'ROLE_INACTIVE',
    ROLE_READ = 'ROLE_READ',
    ROLE_DELETE = 'ROLE_DELETE',

    PERMISSION_READ = 'PERMISSION_READ',
    PERMISSION_UPDATE = 'PERMISSION_UPDATE',
    PERMISSION_ACTIVE = 'PERMISSION_ACTIVE',
    PERMISSION_INACTIVE = 'PERMISSION_INACTIVE',

    SETTING_READ = 'SETTING_READ',
    SETTING_UPDATE = 'SETTING_UPDATE',
}
