export enum ENUM_API_KEY_STATUS_CODE_ERROR {
    API_KEY_NEEDED_ERROR = 5120,
    API_KEY_PREFIX_INVALID_ERROR = 5121,
    API_KEY_SCHEMA_INVALID_ERROR = 5122,
    API_KEY_TIMESTAMP_NOT_MATCH_WITH_REQUEST_ERROR = 5123,
    API_KEY_NOT_FOUND_ERROR = 5124,
    API_KEY_INACTIVE_ERROR = 5125,
    API_KEY_INVALID_ERROR = 5126,
    API_KEY_PASSPHRASE_NOT_FOUND_ERROR = 5128,
    API_KEY_PASSPHRASE_INVALID_ERROR = 5129,
}
