@base_url = http://127.0.0.1:3000
@api_prefix = /api/v1
@api_key = local_fyFGb7ywyM37TqDY8nuhAmGW5:qbp7LmCxYUTHFwKvHnxGW1aTyjSNU6ytN21etK89MaP2Dj2KZP
#@email = admin@mail.com
#@password = aaAA@123
@email = invited-user@example.com
@password = aaAA@123
@from = website
@admin_tenant_id = 6995f75d40c4a96b6873b250
@tenant_member_user_id = <USER_ID>
@tenant_member_id = <TENANT_MEMBER_ID>
@tenant_member_role_name = tenant-user
@tenant_member_role_id = 698fac3f5abe74fea1ecdda3
@invite_email = invited-user@example.com
### @tenant_id = 6995f75d40c4a96b6873b250

### Tenant - login with credentials
POST {{base_url}}{{api_prefix}}/public/tenants/login/credential
X-Api-Key: {{api_key}}
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "from": "{{from}}"
}
> {%
  const data = response.body?.data ?? {};
  const accessToken = data?.tokens?.accessToken;
  const refreshToken = data?.tokens?.refreshToken;
  const tenantId = data?.tenants?.[0]?.tenantId ?? data?.tenantId;

  if (accessToken) client.global.set("jwt_token", accessToken);
  if (refreshToken) client.global.set("refresh_token", refreshToken);
  if (tenantId) client.global.set("tenant_id", tenantId);
%}

### Tenant Shared - current tenant
GET {{base_url}}{{api_prefix}}/shared/tenants/current
X-Api-Key: {{api_key}}
Authorization: Bearer {{jwt_token}}
X-Tenant-Id: {{tenant_id}}

### Tenant Shared - update current tenant
PATCH {{base_url}}{{api_prefix}}/shared/tenants/current/tenant
X-Api-Key: {{api_key}}
Authorization: Bearer {{jwt_token}}
X-Tenant-Id: {{tenant_id}}
Content-Type: application/json

{
  "name": "Acme Travel Group - Updated",
  "status": "active"
}

### Tenant Shared - list current tenant members
GET {{base_url}}{{api_prefix}}/shared/tenants/current/members?page=1&perPage=20
X-Api-Key: {{api_key}}
Authorization: Bearer {{jwt_token}}
X-Tenant-Id: {{tenant_id}}

### Tenant Shared - list current tenant member roles
GET {{base_url}}{{api_prefix}}/shared/tenants/current/members/roles
X-Api-Key: {{api_key}}
Authorization: Bearer {{jwt_token}}
X-Tenant-Id: {{tenant_id}}

### Tenant Shared - create tenant member invitation
POST {{base_url}}{{api_prefix}}/shared/tenants/current/members/invites
X-Api-Key: {{api_key}}
Authorization: Bearer {{jwt_token}}
X-Tenant-Id: {{tenant_id}}
Content-Type: application/json

{
  "email": "{{invite_email}}",
  "roleId": "69a4853efd85caf5af677c31"
}



### Tenant Shared - update current tenant member
PATCH {{base_url}}{{api_prefix}}/shared/tenants/current/members/{{tenant_member_id}}
X-Api-Key: {{api_key}}
Authorization: Bearer {{jwt_token}}
X-Tenant-Id: {{tenant_id}}
Content-Type: application/json

{
  "roleId": "{{tenant_member_role_id}}",
  "status": "active"
}

### Tenant Shared - delete current tenant member
DELETE {{base_url}}{{api_prefix}}/shared/tenants/current/members/{{tenant_member_id}}
X-Api-Key: {{api_key}}
Authorization: Bearer {{jwt_token}}
X-Tenant-Id: {{tenant_id}}

### Tenant Admin - list tenants
GET {{base_url}}{{api_prefix}}/admin/tenants?page=1&perPage=20
X-Api-Key: {{api_key}}
Authorization: Bearer {{jwt_token}}

### Tenant Admin - create tenant
POST {{base_url}}{{api_prefix}}/admin/tenants
X-Api-Key: {{api_key}}
Authorization: Bearer {{jwt_token}}
Content-Type: application/json

{
  "name": "Acme Travel Group #2"
}

### Tenant Admin - get tenant
GET {{base_url}}{{api_prefix}}/admin/tenants/{{admin_tenant_id}}
X-Api-Key: {{api_key}}
Authorization: Bearer {{jwt_token}}

### Tenant Admin - update tenant
PATCH {{base_url}}{{api_prefix}}/admin/tenants/{{admin_tenant_id}}
X-Api-Key: {{api_key}}
Authorization: Bearer {{jwt_token}}
Content-Type: application/json

{
  "name": "Acme Travel Group - APAC",
  "status": "active"
}

### Tenant Admin - delete tenant (soft delete)
DELETE {{base_url}}{{api_prefix}}/admin/tenants/{{admin_tenant_id}}
X-Api-Key: {{api_key}}
Authorization: Bearer {{jwt_token}}
