export enum ENUM_HELPER_IMAGE {
    JPG = 'JPG',
    JPEG = 'JPEG',
    PNG = 'PNG'
}

export enum ENUM_HELPER_STATUS_CODE_ERROR {
    HELPER_IMAGE_NEEDED_ERROR = 5800,
    HELPER_IMAGE_MAX_SIZE_ERROR = 5801,
    HELPER_IMAGE_EXTENSION_ERROR = 5802
}
