export enum ENUM_ROLE_STATUS_CODE_ERROR {
    ROLE_NOT_FOUND_ERROR = 5100,
    ROLE_PAYLOAD_TYPE_INVALID_ERROR = 5101,
    ROLE_EXIST_ERROR = 5102,
    ROLE_IS_ACTIVE_ERROR = 5103,
    ROLE_INACTIVE_ERROR = 5104,
    ROLE_USED_ERROR = 5105,
}
