import { ApiProperty } from '@nestjs/swagger';
import { IsNotEmpty, IsString, Matches } from 'class-validator';

export class UserTwoFactorConfirmRequestDto {
    @ApiProperty({
        description: '6 digit code generated by the authenticator app',
        example: '123456',
        minLength: 6,
        maxLength: 8,
    })
    @IsString()
    @IsNotEmpty()
    @Matches(/^[0-9]{6,8}$/)
    code: string;
}
