export enum ENUM_REQUEST_STATUS_CODE_ERROR {
    REQUEST_VALIDATION_ERROR = 5981,
    REQUEST_TIMESTAMP_INVALID_ERROR = 5982,
    REQUEST_USER_AGENT_INVALID_ERROR = 5983,
}

export const REQUEST_EXCLUDE_TIMESTAMP_META_KEY =
    'RequestExcludeTimestampMetaKey';
