export enum ENUM_REQUEST_STATUS_CODE_ERROR {
    REQUEST_VALIDATION_ERROR = 5981,
    REQUEST_TIMESTAMP_INVALID_ERROR = 5982,
    REQUEST_USER_AGENT_INVALID_ERROR = 5983,
}

export enum ENUM_REQUEST_METHOD {
    GET = 'GET',
    POST = 'POST',
    PUT = 'PUT',
    PATCH = 'PATCH',
    DELETE = 'DELETE',
    OPTIONS = 'OPTIONS',
    HEAD = 'HEAD',
}

export const REQUEST_EXCLUDE_TIMESTAMP_META_KEY =
    'RequestExcludeTimestampMetaKey';
