import { GetTemplateCommandOutput } from '@aws-sdk/client-ses';

export interface IEmailTemplateService {
    importChangePassword(): Promise<boolean>;
    getChangePassword(): Promise<GetTemplateCommandOutput | null>;
    deleteChangePassword(): Promise<boolean>;
    importWelcome(): Promise<boolean>;
    getWelcome(): Promise<GetTemplateCommandOutput | null>;
    deleteWelcome(): Promise<boolean>;
    importCreateByAdmin(): Promise<boolean>;
    getCreateByAdmin(): Promise<GetTemplateCommandOutput | null>;
    deleteCreateByAdmin(): Promise<boolean>;
    importTemporaryPasswordByAdmin(): Promise<boolean>;
    getTemporaryPasswordByAdmin(): Promise<GetTemplateCommandOutput | null>;
    deleteTemporaryPasswordByAdmin(): Promise<boolean>;
    importResetPassword(): Promise<boolean>;
    getResetPassword(): Promise<GetTemplateCommandOutput | null>;
    deleteResetPassword(): Promise<boolean>;
    importForgotPassword(): Promise<boolean>;
    getForgotPassword(): Promise<GetTemplateCommandOutput | null>;
    deleteForgotPassword(): Promise<boolean>;
    importVerification(): Promise<boolean>;
    getVerification(): Promise<GetTemplateCommandOutput | null>;
    deleteVerification(): Promise<boolean>;
    importEmailVerified(): Promise<boolean>;
    getEmailVerified(): Promise<GetTemplateCommandOutput | null>;
    deleteEmailVerified(): Promise<boolean>;
    importMobileNumberVerified(): Promise<boolean>;
    getMobileNumberVerified(): Promise<GetTemplateCommandOutput | null>;
    deleteMobileNumberVerified(): Promise<boolean>;
    importResetTwoFactorByAdmin(): Promise<boolean>;
    getResetTwoFactorByAdmin(): Promise<GetTemplateCommandOutput | null>;
    deleteResetTwoFactorByAdmin(): Promise<boolean>;
    importNewDeviceLogin(): Promise<boolean>;
    getNewDeviceLogin(): Promise<GetTemplateCommandOutput | null>;
    deleteNewDeviceLogin(): Promise<boolean>;
    importPublishTermPolicy(): Promise<boolean>;
    getTermPolicy(): Promise<GetTemplateCommandOutput | null>;
    deleteTermPolicy(): Promise<boolean>;
}
