export enum ENUM_PAGINATION_ORDER_DIRECTION_TYPE {
    ASC = 'asc',
    DESC = 'desc',
}

export enum ENUM_PAGINATION_FILTER_DATE_TIME_OPTIONS {
    START_OF_DAY = 'START_OF_DAY',
    END_OF_DAY = 'END_OF_DAY',
}
