export enum ENUM_USER_STATUS_CODE_ERROR {
    USER_NOT_FOUND_ERROR = 5400,
    USER_USERNAME_EXISTS_ERROR = 5401,
    USER_EMAIL_EXIST_ERROR = 5402,
    USER_MOBILE_NUMBER_EXIST_ERROR = 5403,
    USER_IS_ACTIVE_ERROR = 5404,
    USER_INACTIVE_ERROR = 5405,
    USER_PASSWORD_NOT_MATCH_ERROR = 5406,
    USER_PASSWORD_NEW_MUST_DIFFERENCE_ERROR = 5407,
    USER_PASSWORD_EXPIRED_ERROR = 5408,
    USER_PASSWORD_ATTEMPT_MAX_ERROR = 5409,
}
