export enum ENUM_USER_SIGN_UP_FROM {
    ADMIN = 'ADMIN',
    PUBLIC = 'PUBLIC',
    SEED = 'SEED',
}

export enum ENUM_USER_STATUS {
    CREATED = 'CREATED',
    ACTIVE = 'ACTIVE',
    INACTIVE = 'INACTIVE',
    DELETED = 'DELETED',
    BLOCKED = 'BLOCKED',
}

export enum ENUM_USER_GENDER {
    MALE = 'MALE',
    FEMALE = 'FEMALE',
}

export enum ENUM_USER_PASSWORD_TYPE {
    SIGN_UP_PASSWORD = 'SIGN_UP_PASSWORD',
    FORGOT_PASSWORD = 'FORGOT_PASSWORD',
    TEMPORARY_PASSWORD = 'TEMPORARY_PASSWORD',
    CHANGE_PASSWORD = 'CHANGE_PASSWORD',
}
