import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const rootDir = path.resolve(import.meta.dirname, '..');
const outputDir = path.join(rootDir, 'src', 'generated', 'package');
const pkg: Record<string, unknown> = JSON.parse(
    readFileSync(path.join(rootDir, 'package.json'), 'utf8')
);

mkdirSync(outputDir, { recursive: true });
writeFileSync(
    path.join(outputDir, 'package.ts'),
    [
        '/* !!! This is code generated by scripts/generate-package.ts. Do not edit directly. !!! */',
        '/* eslint-disable */',
        '',
        `export const version: string = ${JSON.stringify(pkg.version)};`,
        `export const author: { name: string; email: string } = ${JSON.stringify(pkg.author)};`,
        `export const repository: { type: string; url: string } = ${JSON.stringify(pkg.repository)};`,
        '',
    ].join('\n')
);
