# Test Image
FROM node:lts-alpine as builder
LABEL maintainer "andrechristikan@mail.com"

ENV NODE_ENV=test

WORKDIR /app
COPY package.json yarn.lock ./

RUN set -x && yarn --frozen-lockfile --non-interactive

COPY . .

RUN yarn build

# Production Image
FROM node:lts-alpine as main
LABEL maintainer "andrechristikan@mail.com"

ENV NODE_ENV=${NODE_ENV}

WORKDIR /app
EXPOSE 3000

COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/dist ./dist
RUN touch .env

RUN set -x && yarn --frozen-lockfile --non-interactive --production

CMD ["yarn", "start:prod"]
