FROM node:lts-alpine
LABEL maintainer="andrechristikan@gmail.com"

WORKDIR /app

RUN corepack enable
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

RUN set -x && pnpm install --frozen-lockfile

RUN touch .env

COPY . .

RUN pnpm db:generate

EXPOSE 3000

CMD [ "pnpm", "start:dev" ]
