export enum ENUM_PERMISSION_STATUS_CODE_ERROR {
    PERMISSION_NOT_FOUND_ERROR = 5200,
    PERMISSION_GUARD_INVALID_ERROR = 5201,
    PERMISSION_IS_ACTIVE_ERROR = 5202,
    PERMISSION_INACTIVE_ERROR = 5203,
}
