export enum ENUM_FILE_STATUS_CODE_ERROR {
    FILE_NEEDED_ERROR = 5950,
    FILE_MAX_SIZE_ERROR = 5951,
    FILE_EXTENSION_ERROR = 5952,
    FILE_MAX_ERROR = 5953,
    FILE_VALIDATION_DTO_ERROR = 5954,
    FILE_NEED_EXTRACT_FIRST_ERROR = 5955,
}
