export enum ENUM_FILE_STATUS_CODE_ERROR {
    FILE_NEEDED_ERROR = 5030,
    FILE_MAX_SIZE_ERROR = 5031,
    FILE_EXTENSION_ERROR = 5032,
    FILE_MAX_FILES_ERROR = 5033,
    FILE_VALIDATION_DTO_ERROR = 5034,
    FILE_NEED_EXTRACT_FIRST_ERROR = 5035,
    FILE_VALIDATION_ALL_SHEET_DTO_ERROR = 5036,
}
