export enum ENUM_PAGINATION_AVAILABLE_SORT_TYPE {
    ASC = 'ASC',
    DESC = 'DESC',
}

export enum ENUM_PAGINATION_TYPE {
    FULL = 'FULL',
    SIMPLE = 'SIMPLE',
    MINI = 'MINI',
}

export enum ENUM_PAGINATION_FILTER_CASE_OPTIONS {
    UPPERCASE = 'UPPERCASE',
    LOWERCASE = 'LOWERCASE',
}
