export enum ENUM_REQUEST_STATUS_CODE_ERROR {
    REQUEST_VALIDATION_ERROR = 5981,
    REQUEST_TIMESTAMP_INVALID_ERROR = 5982,
    REQUEST_USER_AGENT_INVALID_ERROR = 5983,
    REQUEST_USER_AGENT_OS_INVALID_ERROR = 5984,
    REQUEST_USER_AGENT_BROWSER_INVALID_ERROR = 5985,
}
