export enum ENUM_REQUEST_STATUS_CODE_ERROR {
    REQUEST_VALIDATION_ERROR = 5070,
    REQUEST_TIMESTAMP_INVALID_ERROR = 5071,
    REQUEST_USER_AGENT_INVALID_ERROR = 5072,
    REQUEST_USER_AGENT_OS_INVALID_ERROR = 5073,
    REQUEST_USER_AGENT_BROWSER_INVALID_ERROR = 5074,
}
